config/routes.rb
Rails.application.routes.draw do
  resources :orderitems
  resources :orders
  resources :cart_with_items
  resources :carts
  resources :items
  resources :dashboard
  devise_for :users
  root to: "home#index"

end

app/models/orderitem.rb
class Orderitem < ActiveRecord::Base
  belongs_to :order
  belongs_to :item
end

app/controllers/orderitems_controller.rb
class OrderitemsController < ApplicationController
  before_action :set_orderitem, only: [:show, :edit, :update, :destroy]

  # GET /orderitems
  # GET /orderitems.json
  def index
    @orderitems = Orderitem.all
  end

  # GET /orderitems/1
  # GET /orderitems/1.json
  def show
  end

  # GET /orderitems/new
  def new
    @orderitem = Orderitem.new
  end

  # GET /orderitems/1/edit
  def edit
  end

  # POST /orderitems
  # POST /orderitems.json
  def create
    @orderitem = Orderitem.new(orderitem_params)

    respond_to do |format|
      if @orderitem.save
        format.html { redirect_to @orderitem, notice: 'Orderitem was successfully created.' }
        format.json { render :show, status: :created, location: @orderitem }
      else
        format.html { render :new }
        format.json { render json: @orderitem.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /orderitems/1
  # PATCH/PUT /orderitems/1.json
  def update
    respond_to do |format|
      if @orderitem.update(orderitem_params)
        format.html { redirect_to @orderitem, notice: 'Orderitem was successfully updated.' }
        format.json { render :show, status: :ok, location: @orderitem }
      else
        format.html { render :edit }
        format.json { render json: @orderitem.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /orderitems/1
  # DELETE /orderitems/1.json
  def destroy
    @orderitem.destroy
    respond_to do |format|
      format.html { redirect_to orderitems_url, notice: 'Orderitem was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_orderitem
      @orderitem = Orderitem.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def orderitem_params
      params.require(:orderitem).permit(:order_id, :item_id)
    end
end

app/helpers/orderitems_helper.rb
module OrderitemsHelper
end

app/views/orderitems/_form.html.erb
<%= form_for(@orderitem) do |f| %>
  <% if @orderitem.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@orderitem.errors.count, "error") %> prohibited this orderitem from being saved:</h2>

      <ul>
      <% @orderitem.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :order_id %><br>
    <%= f.text_field :order_id %>
  </div>
  <div class="field">
    <%= f.label :item_id %><br>
    <%= f.text_field :item_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/orderitems/edit.html.erb
<h1>Editing Orderitem</h1>

<%= render 'form' %>

<%= link_to 'Show', @orderitem %> |
<%= link_to 'Back', orderitems_path %>

app/views/orderitems/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Orderitems</h1>

<table>
  <thead>
    <tr>
      <th>Order</th>
      <th>Item</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @orderitems.each do |orderitem| %>
      <tr>
        <td><%= orderitem.order %></td>
        <td><%= orderitem.item %></td>
        <td><%= link_to 'Show', orderitem %></td>
        <td><%= link_to 'Edit', edit_orderitem_path(orderitem) %></td>
        <td><%= link_to 'Destroy', orderitem, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Orderitem', new_orderitem_path %>

app/views/orderitems/new.html.erb
<h1>New Orderitem</h1>

<%= render 'form' %>

<%= link_to 'Back', orderitems_path %>

app/views/orderitems/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Order:</strong>
  <%= @orderitem.order %>
</p>

<p>
  <strong>Item:</strong>
  <%= @orderitem.item %>
</p>

<%= link_to 'Edit', edit_orderitem_path(@orderitem) %> |
<%= link_to 'Back', orderitems_path %>