config/routes.rb
Rails.application.routes.draw do
  resources :orderitems
  resources :orders
  resources :cart_with_items
  resources :carts
  resources :items
  resources :dashboard
  devise_for :users
  root to: "home#index"

end

app/models/cart_with_item.rb
class CartWithItem < ActiveRecord::Base
  belongs_to :user
  belongs_to :cart
end

app/controllers/cart_with_items_controller.rb
class CartWithItemsController < ApplicationController
  before_action :set_cart_with_item, only: [:show, :edit, :update, :destroy]

  # GET /cart_with_items
  # GET /cart_with_items.json
 def index
    @cart_with_items = CartWithItem.all
  end

  # GET /cart_with_items/1
  # GET /cart_with_items/1.json
  #def show
  #end

  # GET /cart_with_items/new
  

  # GET /cart_with_items/1/edit
  def edit
  end

  # POST /cart_with_items
  # POST /cart_with_items.json
  def create
    @cart_with_item = CartWithItem.new(cart_with_item_params)

    respond_to do |format|
      if @cart_with_item.save
        format.html { redirect_to @cart_with_item, notice: 'Cart with item was successfully created.' }
        format.json { render :show, status: :created, location: @cart_with_item }
      else
        format.html { render :new }
        format.json { render json: @cart_with_item.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /cart_with_items/1
  # PATCH/PUT /cart_with_items/1.json
  def update
    respond_to do |format|
      if @cart_with_item.update(cart_with_item_params)
        format.html { redirect_to @cart_with_item, notice: 'Cart with item was successfully updated.' }
        format.json { render :show, status: :ok, location: @cart_with_item }
      else
        format.html { render :edit }
        format.json { render json: @cart_with_item.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /cart_with_items/1
  # DELETE /cart_with_items/1.json
  def destroy
    @cart_with_item.destroy
    respond_to do |format|
      format.html { redirect_to cart_with_items_url, notice: 'Cart with item was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_cart_with_item
      @cart_with_item = CartWithItem.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def cart_with_item_params
      params.require(:cart_with_item).permit(:quantity, :user_id, :cart_id)
    end
end

app/helpers/cart_with_items_helper.rb
module CartWithItemsHelper
end

app/views/cart_with_items/_form.html.erb
<%= form_for(@cart_with_item) do |f| %>
  <% if @cart_with_item.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@cart_with_item.errors.count, "error") %> prohibited this cart_with_item from being saved:</h2>

      <ul>
      <% @cart_with_item.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :quantity %><br>
    <%= f.number_field :quantity %>
  </div>
  <div class="field">
    <%= f.label :user_id %><br>
    <%= f.text_field :user_id %>
  </div>
  <div class="field">
    <%= f.label :cart_id %><br>
    <%= f.text_field :cart_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/cart_with_items/edit.html.erb
<h1>Editing Cart With Item</h1>

<%= render 'form' %>

<%= link_to 'Show', @cart_with_item %> |
<%= link_to 'Back', cart_with_items_path %>

app/views/cart_with_items/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Cart With Items</h1>

<table>
  <thead>
    <tr>
      <th>Quantity</th>
      <th>User</th>
      <th>Cart</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @cart_with_items.each do |cart_with_item| %>
      <tr>
        <td><%= cart_with_item.quantity %></td>
        <td><%= cart_with_item.user %></td>
        <td><%= cart_with_item.cart %></td>
        <td><%= link_to 'Show', cart_with_item %></td>
        <td><%= link_to 'Edit', edit_cart_with_item_path(cart_with_item) %></td>
        <td><%= link_to 'Destroy', cart_with_item, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Cart with item', new_cart_with_item_path %>

app/views/cart_with_items/new.html.erb
<h1>New Cart With Item</h1>

<%= render 'form' %>

<%= link_to 'Back', cart_with_item_path %>

app/views/cart_with_items/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Quantity:</strong>
  <%= @cart_with_item.quantity %>
</p>

<p>
  <strong>User:</strong>
  <%= @cart_with_item.user %>
</p>

<p>
  <strong>Cart:</strong>
  <%= @cart_with_item.cart %>
</p>

<%= link_to 'Edit', edit_cart_with_item_path(@cart_with_item) %> |
<%= link_to 'Back', cart_with_items_path %>